### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE] in zsh-history-enquirer/index.js:7

### ISSUE THREAD

**Issue by aemartinez** [zthxxx/zsh-history-enquirer#59]
I installed `jovial` using the installation script (`curl -sSL https://github.com/zthxxx/jovial/raw/master/installer.sh | sudo -E bash -s $USER`). This installed` zsh-history-enquirer`. 

When I try to access the history via `^R` I get the following error message:

```
/usr/local/lib/node_modules/zsh-history-enquirer/index.js:7
    throw err
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:209:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/zsh-history-enquirer/dist/index.js:1746:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/zsh-history-enquirer/index.js:3:17)
```

I'm running macOS Monterey v12.6. (`Darwin -- 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:05 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8101 arm64`).

Do you know what I might be doing wrong? Or is this an actual bug?

Thanks for your work :)

**Comment by zthxxx** [comment]
@aemartinez  what's the version of your Nodejs?  It's seems `require('stream').pipeline` is not a function in your Nodejs

**Comment by aemartinez** [comment]
Thanks! Upgrading Nodejs solved the problem. I had version `v8.11`, I upgrade it with `brew install node` and it installed `v18.11.0`, which works. For some reason the installation of `jovial` didn't upgrade Node?

**Comment by zthxxx** [comment]
Aha, It's support over Nodejs >= v12 😂  The version v8 is so out of date, and `jovial`
